cluster-api/third_party/forked/rerun-process-wrapper: cluster-api
	mkdir -p cluster-api/third_party/forked/rerun-process-wrapper
	cp -R third_party/forked/rerun-process-wrapper/* cluster-api/third_party/forked/rerun-process-wrapper
	echo third_party/forked/rerun-process-wrapper >> cluster-api/.git/info/exclude
